### ISSUE TITLE
projectMap is sometimes null

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-fims-commons#1]
in ProjectMinter.getMyTemplatesAndDatasets() projectMap, line 627 sometimes a null pointer is thrown.  For some reason the projectMap is null and throws an error... i added a try/catch statement so it wouldn't break things.  See if this can be replicated using a local database, if not, i can dump a database that will reproduce the error.

**Comment by rodney757** [comment]
I suspect that this has to do with the fact that in nmnh-fims, the user can upload to expeditions that they do not own. The projectMap is built using only expeditions that the user owns.

This should be fixed with commit 74861c6d8632ea2436efda483e03b5c757ede5a1
