### ISSUE TITLE
Able to attach a dataset to an expedition for not public expedition

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-fims-commons#16]
Currently services allow attaching a dataset to an expedition that is not public and not owned by that user.  User A creates expedition and sets not public.  User B then attempts to attach a dataset to same expedition title and is able to do so.   This should actually be an error

**Comment by rodney757** [comment]
do we want to allow uploading to public expeditions?

**Comment by jdeck88** [comment]
Uploading should always require authentication from project users

On Wednesday, May 4, 2016, RJ Ewing <notifications@github.com> wrote:

> do we want to allow uploading to public expeditions?
>
> On Sat, Apr 30, 2016 at 1:37 PM, John Deck <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Assigned #16
> > <https://github.com/biocodellc/biocode-fims-commons/issues/16> to
> > @rodney757 <https://github.com/rodney757>.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/biocodellc/biocode-fims-commons/issues/16#event-646615599
> >
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/biocodellc/biocode-fims-commons/issues/16#issuecomment-216992474>
>


-- 
John Deck
(541) 914-4739

**Comment by rodney757** [comment]
right, but should an authenticated user be able to upload a dataset to an
expedition they do not own if the expedition is public? Or should they only
be able to upload to expeditions they own? I thought it was the later, but
the title of this issue has me second guessing

**Comment by jdeck88** [comment]
Yes the latter

On Wednesday, May 4, 2016, RJ Ewing <notifications@github.com> wrote:

> right, but should an authenticated user be able to upload a dataset to an
> expedition they do not own if the expedition is public? Or should they only
> be able to upload to expeditions they own? I thought it was the later, but
> the title of this issue has me second guessing
>
> On Wed, May 4, 2016 at 2:21 PM, John Deck <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Uploading should always require authentication from project users
> >
> > On Wednesday, May 4, 2016, RJ Ewing <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > do we want to allow uploading to public expeditions?
> > >
> > > On Sat, Apr 30, 2016 at 1:37 PM, John Deck <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > >
> > > > Assigned #16
> > > > <https://github.com/biocodellc/biocode-fims-commons/issues/16> to
> > > > @rodney757 <https://github.com/rodney757>.
> > > >
> > > > —
> > > > You are receiving this because you were mentioned.
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/biocodellc/biocode-fims-commons/issues/16#event-646615599
> > > >
> > > >
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/biocodellc/biocode-fims-commons/issues/16#issuecomment-216992474
> > >
> > >
> >
> >
> > --
> > John Deck
> > (541) 914-4739
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/biocodellc/biocode-fims-commons/issues/16#issuecomment-217006662
> >
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/biocodellc/biocode-fims-commons/issues/16#issuecomment-217017779>
>


-- 
John Deck
(541) 914-4739

**Comment by rodney757** [comment]
fixed in commit 61bc6f1770baa5507ad43837b03470252ff9a0b5
