### ISSUE TITLE
Bug in validation engine on the attached spreadsheet.

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-fims-commons#20]
The attached file, in the column "intentToCollectOtherDatatypes" (which is bad data, i know) causes the validation processor to respond with spreadsheet failed initial check.  This is a pretty cryptic error message and should respond perhaps with "Bad column values found in this column" or something more helpful like that.  
[PNGOA-ARMS-Metadata-pCM (1).xlsx](https://github.com/biocodellc/biocode-fims-commons/files/321581/PNGOA-ARMS-Metadata-pCM.1.xlsx)

**Comment by rodney757** [comment]
Hmm, I can't seem to reproduce this either locally or on biscicol

**Comment by jdeck88** [comment]
Try on ARMS
at http://biscicol.org/arms/
John

On Tue, Jun 21, 2016 at 3:28 PM, RJ Ewing <notifications@github.com> wrote:

> Hmm, I can't seem to reproduce this either locally or on biscicol
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/biocodellc/biocode-fims-commons/issues/20#issuecomment-227591548>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABGdxUirms1_P6hvIdgG8nF_fjx9P37Fks5qOGWSgaJpZM4I43GY>
> .
>



-- 
John Deck
(541) 914-4739

**Comment by rodney757** [comment]
I did.

However looking at the attached spreadsheet, I don't see a "intentToCollectOtherDatatypes" column. Maybe you attached the wrong sheet?

**Comment by jdeck88** [comment]
Sorry, looks like i uploaded a sheet where this column was dropped.  Try the one attached to this comment.
[PNGOA-ARMS-Metadata-p.xlsx](https://github.com/biocodellc/biocode-fims-commons/files/335263/PNGOA-ARMS-Metadata-p.xlsx)

**Comment by rodney757** [comment]
okay, this is fixed. There is now a more informative message being passed to the user
