### ISSUE TITLE
Cannot create BCIDs using the BCIDCreator

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-fims-commons#21]
At http://biscicol.org/bcidCreator

This throws a java.lang.NoSuchFieldError: DEF_CONTENT_CHARSET in the logs.

Some online message boards point to httpclient and httpcore version conflicts of which we have.

**Comment by rodney757** [comment]
fixed with commit f618fd6 and biscicol commit affecting gradle dependency resolution
