### ISSUE TITLE
query service does not return results properly

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-fims-commons#29]
Querying a private project and public expedition while logged in as one of the project users does not return results from the following query:

http://biscicol.org/biocode-fims/rest/projects/query/json?project_id=32&filter=BDGuiana

The above was tried while authenticated as ggi_admin and did not work.
Briefly setting project status to "public" did make this query work, however,

Results are "unauthorized query" status code 403.

**Comment by rodney757** [comment]
If you called that url exactly, there is no authentication information
provided, so the unauthorized query is to be expected. You need to either
have an accessToken in the url or pass the login cookies to the REST
endpoint.
