### ISSUE TITLE
discuss create new resource bcids during uploading

### ISSUE THREAD

**Issue by rodney757** [biocodellc/biocode-fims-commons#31]
Currently if you add a new entity to a project configuration, and then upload data to an existing expedition in the project, there is not a resource bcid for the newly added entity.

This issue is to discuss if we want to create resource bcids during upload if the project configuration has changed

**Comment by jdeck88** [comment]
This is a good idea.  If the project configuration changes alot then we will have some issues with querying data-sources.  However, most of the entity/resource changes will not break the core model. Guess we just have to be careful about what changes are introduced in the configuration file.

**Comment by rodney757** [comment]
this is handled in new backed (psql branch)
