### ISSUE TITLE
validation project selection issues

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-fims-commons#5]
In the validation interface, it is possible to FIRST choose a project before selecting a spreadsheet.  If this is done, however, it throws an error saying that it can't read the dataset code in the spreadsheet (because the user hasn't selected it).   To fix this, disable the check/message itself.  Allow the user to set the project as they will without checking the dataset code -- this check can be done on submit.

**Comment by rodney757** [comment]
okay, so I think this is an nmnh-fims issue. What is the desired behavior? 

1. Throw an error if the dataset_code isn't in the spreadsheet? 
2. Let the user enter the dataset_code if it isn't in the spreadsheet?
3. What about for older browsers that don't support the file reader needed to check the spreadsheet for the dataset code? 

For now, I changed the project select to be hidden when there is no spreadsheet selected, thus avoiding the original error. If you prefer something else, I can change it to your original request when you answer the above questions
