### ISSUE TITLE
Expedition Resources Minted Multiple Times

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-fims-commons#7]
These should just be created once... there are cases here where they are getting minted (it appears) each time an upload happens. See attached screenshot for an example from demo account:

[expeditions.pdf](https://github.com/biocodellc/biocode-fims-commons/files/144884/expeditions.pdf)

**Comment by rodney757** [comment]
fixed with commit 96b4b71d09237eb2c5c32f58b163bdb590d8a99b
