### ISSUE TITLE
first time logging into site does not take

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-fims-commons#8]
after logging into biscicol.org it doesn't take.  it redirects you to homepage and you are not logged in.  However, if you try again, it works.  Not sure if this is a biscicol front end issue or a fims commons issue.

**Comment by jdeck88** [comment]
this is actually fixed now..i redeployed and tested and it works.

**Comment by rodney757** [comment]
Ah, I accidentally commented out the cookie-config domain param in the web.xml in a commit. I need to do this locally, but shouldn't have committed it.
